//! The suite has teeth: each defect planted in the mock fails the scenario written for
//! it. The defects are every one the audits found in a plausible engine or viewer.
//! Against the honest mock every scenario passes (`adversary.rs`).

#![allow(clippy::unwrap_used, clippy::expect_used)]

use nfx_pay::adversary;
use nfx_pay::mock::{MockHarness, SeederFlaw as S, ViewerFlaw as V};

macro_rules! catches {
    ($($test:ident: $harness:expr => $scenario:ident),* $(,)?) => {
        $(
            #[tokio::test]
            async fn $test() {
                let run = tokio::spawn(async { adversary::$scenario(&$harness).await });
                // A scenario that hangs on the defect has caught it too: the suite's own
                // runner fails a hung scenario.
                match tokio::time::timeout(std::time::Duration::from_secs(10), run).await {
                    Err(_hung) => {}
                    Ok(joined) => assert!(
                        joined.as_ref().is_err_and(tokio::task::JoinError::is_panic),
                        "{} did not catch the planted defect",
                        stringify!($scenario)
                    ),
                }
            }
        )*
    };
}

fn s(flaw: S) -> MockHarness {
    MockHarness::with_seeder_flaw(flaw)
}

fn v(flaw: V) -> MockHarness {
    MockHarness::with_viewer_flaw(flaw)
}

catches!(
    overpay_accepted: s(S::AcceptsOverpay) => overpaid_is_refused_and_credits_nothing,
    foreign_mint_accepted: s(S::AcceptsForeignMint) => foreign_and_lookalike_mints_are_refused,
    prefix_mint_match: s(S::PrefixMint) => foreign_and_lookalike_mints_are_refused,
    dleq_at_the_tokens_mint: s(S::DleqAtTokenMint) => foreign_and_lookalike_mints_are_refused,
    bad_tokens_accepted: s(S::AcceptsBadTokens) => bad_tokens_are_refused,
    missing_dleq_accepted: s(S::NoDleqAccepted) => bad_tokens_are_refused,
    forged_proof_not_banned: s(S::InvalidNoBan) => bad_tokens_are_refused,
    spent_without_ban: s(S::NoBanOnSpent) => a_double_spend_bans_the_peer,
    spent_check_on_the_last_proof: s(S::SpentCheckLastProof) => a_double_spend_bans_the_peer,
    swaps_the_unspent_subset: s(S::SwapsUnspentSubset) => a_double_spend_bans_the_peer,
    window_off_by_one: s(S::WindowOffByOne) => an_unpaid_window_stops_serving,
    claims_before_checking: s(S::ClaimsBeforeChecking) => underpaid_is_refused_and_credits_nothing,
    stale_credited: s(S::IgnoresStale) => a_stale_pay_changes_nothing,
    refusal_credits_overpaid: s(S::RefusalCredits) => overpaid_is_refused_and_credits_nothing,
    refusal_credits_bad_mint: s(S::RefusalCredits) => foreign_and_lookalike_mints_are_refused,
    refusal_advances_the_watermark: s(S::RefusalAdvancesAcked) => underpaid_is_refused_and_credits_nothing,
    refusal_claims_a_proof: s(S::ClaimsOnRefusal) => underpaid_is_refused_and_credits_nothing,
    wrapping_mul: s(S::WrappingMul) => an_overflowing_claim_is_underpaid,
    pay_ignores_ban: s(S::PayIgnoresBan) => a_banned_peer_stays_banned,
    admit_ignores_ban: s(S::AdmitIgnoresBan) => a_banned_peer_stays_banned,
    ban_per_video: s(S::BanPerVideo) => a_banned_peer_stays_banned,
    fresh_window_per_hello: s(S::FreshWindowPerHello) => a_new_hello_continues_the_account,
    quote_forgets_the_account: s(S::QuoteForgetsAccount) => a_new_hello_continues_the_account,
    spent_total_per_session: s(S::SpentTotalPerSession) => a_new_hello_continues_the_account,
    open_session_id_reused: s(S::SessionIdAnyPeer) => a_session_id_names_one_open_session,
    session_cap_off_by_one: s(S::SessionCapOffByOne) => open_sessions_are_capped_and_released,
    session_cap_for_life: s(S::SessionCapLifetime) => open_sessions_are_capped_and_released,
    hello_for_any_video: s(S::HelloAnyVideo) => only_the_sessions_video_is_admitted,
    counts_distinct_files: s(S::CountsDistinctFiles) => every_request_counts_whole_or_not,
    admits_foreign_chunks: s(S::AdmitsForeignChunks) => only_the_sessions_video_is_admitted,
    window_across_videos: s(S::WindowAcrossVideos) => the_window_is_per_account,
    window_across_videos_stalls: s(S::WindowAcrossVideos) => an_honest_watcher_streams_two_videos_at_once,
    no_global_cap: s(S::NoGlobalCap) => a_global_cap_bounds_free_service,
    global_cap_off_by_one: s(S::GlobalCapGt) => a_global_cap_bounds_free_service,
    global_cap_nets_credit: s(S::GlobalCapNetsCredit) => the_global_cap_holds_whatever_payments_do,
    ban_forgets_debt: s(S::BanForgetsDebt) => the_global_cap_holds_whatever_payments_do,
    cap_before_credit: s(S::CapBeforeCredit) => prepaid_chunks_are_served_whatever_the_cap,
    paid_debt_stays_counted: s(S::PaidDebtStaysCounted) => a_global_cap_bounds_free_service,
    debt_never_ages: s(S::DebtNeverAges) => debt_counts_for_exactly_debt_ttl,
    peer_debt_ages: s(S::PeerDebtAges) => debt_counts_for_exactly_debt_ttl,
    ack_before_swap: s(S::AckBeforeSwap) => service_waits_for_the_swap,
    outage_bans: s(S::OutageBans) => a_mint_outage_is_not_a_ban,
    outage_credits: s(S::OutageCredits) => a_mint_outage_is_not_a_ban,
    spent_total_counts_refusals: s(S::SpentTotalCountsRefused) => underpaid_is_refused_and_credits_nothing,
    concurrent_pays: s(S::ConcurrentPays) => one_accounts_payments_are_serialised,
    too_many_proofs_accepted: s(S::TooManyProofsAccepted) => bad_tokens_are_refused,
    ban_checked_before_the_turn: s(S::BanCheckedBeforeTurn) => a_banned_peer_stays_banned,
    quote_spent_peer_wide: s(S::QuoteSpentPeerWide) => a_new_hello_continues_the_account,
    quote_served_peer_wide: s(S::QuoteServedPeerWide) => a_new_hello_continues_the_account,
    ack_spent_peer_wide: s(S::AckSpentPeerWide) => a_new_hello_continues_the_account,
    session_cap_per_video: s(S::SessionCapPerVideo) => open_sessions_are_capped_and_released,
    covered_peer_wide: s(S::CoveredPeerWide) => credit_covers_only_its_own_video,
    covered_logged_as_debt: s(S::CoveredLoggedAsDebt) => debt_is_freed_exactly_once,
    ages_after_one_second: s(S::AgeTtlOneSecond) => debt_counts_for_exactly_debt_ttl,
    count_freed_twice: s(S::CountFreedTwice) => debt_is_freed_exactly_once,
    count_freed_twice_wrapping: s(S::CountFreedTwiceWrapping) => debt_is_freed_exactly_once,
    claim_then_await_credit: s(S::ClaimThenAwaitCredit) => a_dropped_pay_is_credited_or_never_claimed,
    quote_without_turn: s(S::QuoteWithoutTurn) => an_honest_pair_survives_a_fast_reconnect,
    hello_creates_account: s(S::HelloCreatesAccount) => a_hello_holds_no_state,
    live_keyed_by_peer: s(S::LiveKeyedByPeer) => a_global_cap_bounds_free_service,
    credit_frees_all_debt: s(S::CreditFreesAllDebt) => a_global_cap_bounds_free_service,
    credit_from_snapshot: s(S::CreditFromSnapshot) => service_waits_for_the_swap,
    forgets_paid_accounts: s(S::ForgetsPaidAccounts) => only_never_paid_accounts_are_forgotten,
    no_validate: s(S::NoValidate) => bad_configurations_are_refused,
    no_deadline: s(S::NoDeadline) => a_seeder_answers_within_its_deadline,
    deadline_from_the_swap: s(S::DeadlineFromSwap) => a_seeder_answers_within_its_deadline,
    late_outcome_bans: s(S::LateOutcomeBans) => a_late_outcome_is_credited_never_banned,
    late_claim_not_credited: s(S::LateClaimNotCredited) => a_late_outcome_is_credited_never_banned,
    late_claim_not_credited_severs: s(S::LateClaimNotCredited) => an_honest_pair_survives_a_late_mint,
    late_by_the_flag_only: s(S::LateByFlagOnly) => a_late_outcome_is_credited_never_banned,
    deadline_beats_the_outcome: s(S::DeadlineBeatsSettled) => a_late_outcome_is_credited_never_banned,
    no_takeover: s(S::NoTakeover) => the_deadline_frees_the_account,
    takeover_at_61: s(S::TakeoverAt61) => the_deadline_frees_the_account,
    turn_without_the_clock: s(S::TurnNoClockWatch) => the_deadline_frees_the_account,
    stale_turn_frees: s(S::StaleTurnFrees) => the_deadline_frees_the_account,
    waiting_hellos_uncapped: s(S::HelloWaitUncapped) => the_deadline_frees_the_account,
    bans_never_expire: s(S::BansNeverExpire) => bans_expire_and_state_stays_bounded,
    bans_expire_early: s(S::BanExpiresEarly) => bans_expire_and_state_stays_bounded,
    never_forgets: s(S::NeverForgets) => only_never_paid_accounts_are_forgotten,
    never_forgets_grows: s(S::NeverForgets) => bans_expire_and_state_stays_bounded,
    forgets_open_accounts: s(S::ForgetsOpenAccounts) => only_never_paid_accounts_are_forgotten,
    forgets_at_debt_ttl: s(S::ForgetsAtDebtTtl) => only_never_paid_accounts_are_forgotten,
    forgets_from_the_last_admission: s(S::ForgetsFromLastAdmission) => only_never_paid_accounts_are_forgotten,
    equal_ttls_refused: s(S::EqualTtlRefused) => bad_configurations_are_refused,
    no_cap_ceiling: s(S::NoCapCeiling) => bad_configurations_are_refused,
    no_ban_ttl_check: s(S::NoBanTtlCheck) => bad_configurations_are_refused,
    waiting_hellos_leak_on_drop: s(S::HelloWaitLeaksOnDrop) => the_deadline_frees_the_account,
    forgets_the_unserved: s(S::ForgetsUnserved) => only_never_paid_accounts_are_forgotten,
    forgets_on_the_first_close: s(S::ForgetsOnFirstClose) => only_never_paid_accounts_are_forgotten,
    session_ids_leak: s(S::SessionIdLeaks) => a_session_id_names_one_open_session,
    landed_records_leak: s(S::LandKeepsFinished) => bans_expire_and_state_stays_bounded,
    ban_expiry_resets_accounts: s(S::BanExpiryResetsAccounts) => bans_expire_and_state_stays_bounded,
    keys_without_the_clock: s(S::FetchNoClockWatch) => a_seeder_answers_within_its_deadline,
    sends_after_the_deadline: s(S::SendIgnoresDeadline) => a_seeder_answers_within_its_deadline,
    no_recheck_at_sending: s(S::NoRecheckAtSend) => a_late_outcome_is_credited_never_banned,
    payments_never_take_over: s(S::PayNoTakeover) => the_deadline_frees_the_account,
    bans_without_an_account: s(S::BansWithoutAccount) => a_hello_holds_no_state,
    waiting_kept_empty: s(S::WaitingKeptEmpty) => a_hello_holds_no_state,
    debt_log_untrimmed: s(S::DebtLogUntrimmed) => bans_expire_and_state_stays_bounded,
    no_ttl_ceiling: s(S::NoTtlCeiling) => bad_configurations_are_refused,
    validates_with_loopback: s(S::ValidateAllowsLoopback) => bad_configurations_are_refused,
    recheck_stale_only: s(S::RecheckStaleOnly) => a_late_outcome_is_credited_never_banned,
    viewer_pays_ahead: v(V::PaysAhead) => a_viewer_pays_for_every_request_and_no_more,
    viewer_ignores_bad_ack: v(V::IgnoresBadAck) => a_viewer_stops_on_a_wrong_or_unsolicited_ack,
    viewer_pays_too_late: v(V::PaysAtTheWindow) => an_honest_pair_streams_a_whole_video,
    viewer_pays_at_the_full_window: v(V::PaysAtFullWindow) => an_honest_pair_streams_a_whole_video,
    viewer_second_quote: v(V::AcceptsSecondQuote) => a_viewer_refuses_quotes_it_cannot_honour,
    viewer_unsolicited_ack: v(V::AcceptsUnsolicitedAck) => a_viewer_stops_on_a_wrong_or_unsolicited_ack,
    viewer_ignores_spent_total: v(V::IgnoresSpentTotal) => a_viewer_stops_on_a_wrong_or_unsolicited_ack,
    viewer_accepts_an_inflated_ack: v(V::AckAcceptsInflated) => a_viewer_stops_on_a_wrong_or_unsolicited_ack,
    viewer_no_reclaim: v(V::NoReclaim) => a_viewer_reclaims_a_refused_payment,
    viewer_reclaims_one_proof: v(V::ReclaimsFirstProofOnly) => a_viewer_reclaims_a_refused_payment,
    viewer_reclaims_only_after_spent: v(V::NoReclaimUnlessSpent) => a_viewer_reclaims_a_refused_payment,
    viewer_last_pay_after_stop: v(V::LastPayIgnoresStop) => a_stopped_viewer_pays_nothing,
    viewer_pays_for_refused_requests: v(V::PaysForRefused) => a_viewer_pays_for_every_request_and_no_more,
    viewer_trusts_the_quote: v(V::TrustsQuote) => a_viewer_refuses_quotes_it_cannot_honour,
    viewer_pays_after_a_timeout: v(V::KeepsPayingAfterTimeout) => a_viewer_reclaims_an_unanswered_payment,
    viewer_forgets_its_ledger: v(V::ForgetsLedger) => an_honest_pair_resumes_after_a_reconnect,
    viewer_stops_on_an_outage: v(V::StopsOnOutage) => an_honest_pair_rides_out_a_mint_outage,
    viewer_pays_its_cap: v(V::PaysAtCap) => an_honest_pair_streams_a_whole_video,
    viewer_ignores_the_reclaim: v(V::IgnoresReclaimOutcome) => a_lying_seeder_takes_at_most_one_payment,
    viewer_refused_no_credit: v(V::RefusedNoCredit) => a_viewer_owes_nothing_for_refused_requests,
    viewer_refused_twice: v(V::RefusedTwice) => a_viewer_owes_nothing_for_refused_requests,
    viewer_never_pays_ahead: v(V::NoPayAhead) => a_paying_watcher_gets_through_a_full_cap,
    viewer_resyncs_down: v(V::ResyncsDown) => a_viewer_refuses_quotes_it_cannot_honour,
    viewer_skips_its_cap_on_resume: v(V::SkipsCapOnResume) => a_viewer_refuses_quotes_it_cannot_honour,
    viewer_times_out_early: v(V::TimeoutEarly) => a_viewer_reclaims_an_unanswered_payment,
    viewer_reclaims_at_end: v(V::EndReclaimsNow) => an_honest_pair_survives_a_dropped_connection,
    viewer_forgets_at_end: v(V::EndForgetsPending) => an_honest_pair_survives_a_dropped_connection,
    viewer_retry_ignores_spent: v(V::RetryIgnoresSpent) => a_lying_seeder_takes_at_most_one_payment,
    viewer_last_pay_ignores_reclaim: v(V::LastPayIgnoresReclaim) => a_lying_seeder_takes_at_most_one_payment,
    viewer_pay_ahead_ignores_reclaim: v(V::PayAheadIgnoresReclaim) => a_lying_seeder_takes_at_most_one_payment,
    viewer_pay_ahead_ignores_pending: v(V::PayAheadIgnoresPending) => a_lying_seeder_takes_at_most_one_payment,
    viewer_pay_ahead_unbounded: v(V::PayAheadUnbounded) => a_refusing_seeder_takes_at_most_half_a_window,
    viewer_settles_on_spent_only: v(V::SettleOnSpentOnly) => a_viewer_settles_only_on_an_exact_match,
    viewer_settles_on_upto_only: v(V::SettleOnUptoOnly) => a_viewer_settles_only_on_an_exact_match,
    viewer_times_out_early_by_a_second: v(V::TimeoutAt179) => a_viewer_reclaims_an_unanswered_payment,
    viewer_catch_up_ignores_wait: v(V::CatchUpIgnoresWait) => a_viewer_settles_a_lost_payment_after_180_s,
    viewer_pay_ahead_sticky: v(V::PayAheadSticky) => a_viewer_pays_ahead_only_after_a_refusal,
    viewer_lost_is_final: v(V::LostIsFinal) => an_honest_pair_survives_a_reordered_payment,
    viewer_lost_is_final_late: v(V::LostIsFinal) => an_honest_pair_survives_a_late_mint,
    viewer_forgives_the_lost: v(V::ForgivesLost) => a_lying_seeder_takes_at_most_one_payment,
    viewer_forgives_the_lost_late: v(V::ForgivesLost) => an_honest_pair_survives_a_late_mint,
    viewer_settles_the_lost_on_upto: v(V::SettleLostOnUpto) => a_viewer_settles_only_on_an_exact_match,
    viewer_stops_per_video: v(V::StopPerVideo) => a_watchers_standing_spans_its_videos,
    viewer_reclaim_holds_one_video: v(V::ReclaimPerVideo) => a_watchers_standing_spans_its_videos,
    viewer_in_flight_per_video: v(V::InFlightPerVideo) => a_watchers_standing_spans_its_videos,
    viewer_settles_the_lost_on_spent: v(V::SettleLostOnSpentOnly) => a_viewer_settles_only_on_an_exact_match,
    viewer_settles_the_lost_anywhere: v(V::SettleLostAnyLedger) => a_watchers_standing_spans_its_videos,
    viewer_awaits_on_every_video: v(V::AwaitingQuoteAnyLedger) => a_watchers_standing_spans_its_videos,
    viewer_retries_as_itself: v(V::RetryAsSelf) => a_watchers_standing_spans_its_videos,
    viewer_catches_up_its_own_only: v(V::CatchUpOwnOnly) => a_watchers_standing_spans_its_videos,
    viewer_end_frees_the_slot: v(V::EndClearsInFlight) => a_watchers_standing_spans_its_videos,
    viewer_last_pay_over_another: v(V::LastPayIgnoresOtherInFlight) => a_watchers_standing_spans_its_videos,
    viewer_last_pay_over_its_own: v(V::LastPayIgnoresOwnPending) => a_watchers_standing_spans_its_videos,
    viewer_ignores_unsolicited_rej: v(V::UnsolicitedRejIgnored) => a_watchers_standing_spans_its_videos,
    viewer_no_window_ceiling: v(V::NoWindowCeiling) => a_viewer_refuses_quotes_it_cannot_honour,
    viewer_no_unavailable_budget: v(V::NoUnavailableBudget) => an_unavailable_seeder_gets_three_tries_a_session,
    viewer_hello_refusal_reclaims: v(V::HelloRefusalReclaims) => an_honest_pair_survives_a_refused_hello,
    viewer_timeout_on_an_old_payment: v(V::TimeoutTouchesUnsettled) => an_honest_pair_survives_a_reordered_payment,
    viewer_skips_its_ceiling_on_resume: v(V::SkipsCeilingOnResume) => a_viewer_refuses_quotes_it_cannot_honour,
    viewer_refused_hello_frees_the_slot: v(V::HelloRefusedFreesSlot) => a_watchers_standing_spans_its_videos,
    viewer_settles_the_unsettled_anywhere: v(V::SettleUnsettledAnyLedger) => a_watchers_standing_spans_its_videos,
    viewer_refusal_resets_the_budget: v(V::RefusalResetsUnavailable) => an_unavailable_seeder_gets_three_tries_a_session,
    viewer_pay_ahead_skips_the_budget: v(V::PayAheadSkipsBudget) => an_unavailable_seeder_gets_three_tries_a_session,
    viewer_catch_up_files_under_itself: v(V::CatchUpFilesUnderSelf) => a_watchers_standing_spans_its_videos,
    viewer_stops_on_a_refused_hello: v(V::HelloRefusalStops) => an_honest_pair_survives_a_refused_hello,
    viewer_ack_keeps_the_count: v(V::AckKeepsUnavailable) => an_unavailable_seeder_gets_three_tries_a_session,
    viewer_counts_per_video: v(V::UnavailablePerLedger) => an_unavailable_seeder_gets_three_tries_a_session,
    viewer_last_pay_ignores_the_budget: v(V::LastPayIgnoresBudget) => an_unavailable_seeder_gets_three_tries_a_session,
    viewer_ignores_a_banned_hello: v(V::BannedHelloIgnored) => an_honest_pair_survives_a_refused_hello,
    viewer_unsolicited_rej_reclaims: v(V::UnsolicitedRejReclaimsUnsettled) => an_honest_pair_survives_a_refused_hello,
    viewer_stopped_skips_reclaim: v(V::StoppedSkipsReclaim) => a_stopped_viewer_pays_nothing,
    viewer_budget_not_signalled: v(V::BudgetNotSignalled) => an_unavailable_seeder_gets_three_tries_a_session,
    ban_needs_this_videos_account: s(S::BanNeedsThisAccount) => a_double_spend_bans_the_peer,
    late_claim_keeps_its_debt: s(S::LateClaimKeepsDebt) => a_late_outcome_is_credited_never_banned,
    viewer_stopped_skips_the_unsettled: v(V::StoppedSkipsUnsettled) => a_stopped_viewer_pays_nothing,
    viewer_refused_hello_resets_the_budget: v(V::HelloRefusedResetsBudget) => an_unavailable_seeder_gets_three_tries_a_session,
    viewer_stops_on_an_unknown_hello_code: v(V::UnknownHelloRefusalStops) => an_honest_pair_survives_a_refused_hello,
    viewer_banned_hello_stops_one_video: v(V::BannedHelloStopsLedger) => an_honest_pair_survives_a_refused_hello,
    viewer_blocked_catch_up_files_under_itself: v(V::CatchUpBlockedAsSelf) => a_watchers_standing_spans_its_videos,
);
