//! The pay/1 vectors (`spec/test-vectors/pay1.json`, generated by `pay1.py`), checked
//! natively and on `wasm32`. Pinned with the money code (`crates/ci/check-locked.sh`), with
//! the vectors and the reference reader, so the parser's tests change only with review.

#![allow(clippy::unwrap_used, clippy::expect_used)]

#[cfg(target_arch = "wasm32")]
use wasm_bindgen_test::wasm_bindgen_test as test;

use serde_json::Value;

fn str_of<'a>(v: &'a Value, key: &str) -> &'a str {
    v[key]
        .as_str()
        .unwrap_or_else(|| panic!("{key} is a string"))
}

fn pay1() -> Value {
    serde_json::from_str(include_str!("../../../spec/test-vectors/pay1.json"))
        .expect("pay1.json is JSON")
}

#[test]
fn pay1_messages_parse_as_the_vectors_say() {
    use nfx_proto::pay::{Message, ParseOptions};
    let v = pay1();
    assert_eq!(v["max_line_bytes"], nfx_proto::pay::MAX_LINE_BYTES);
    assert_eq!(v["max_depth"], nfx_proto::pay::MAX_DEPTH);
    let loopback = ParseOptions {
        allow_loopback_http: true,
    };
    let check_valid = |case: &Value, opts: ParseOptions| {
        let name = str_of(case, "name");
        let m = Message::parse_with(str_of(case, "wire"), opts)
            .unwrap_or_else(|e| panic!("{name}: {e}"));
        let line = m
            .to_line_with(opts)
            .unwrap_or_else(|e| panic!("{name} writes: {e}"));
        let back: Value = serde_json::from_str(&line).unwrap();
        assert_eq!(back, case["message"], "{name}");
        assert_eq!(
            Message::parse_with(&line, opts).unwrap(),
            m,
            "{name} round-trips"
        );
    };
    for case in v["valid"].as_array().unwrap() {
        check_valid(case, ParseOptions::default());
    }
    for case in v["valid_with_loopback"].as_array().unwrap() {
        check_valid(case, loopback);
        assert!(
            Message::parse(str_of(case, "wire")).is_err(),
            "{} is refused by default",
            str_of(case, "name")
        );
    }
    for case in v["invalid"].as_array().unwrap() {
        let name = str_of(case, "name");
        for opts in [ParseOptions::default(), loopback] {
            assert!(
                Message::parse_with(str_of(case, "wire"), opts).is_err(),
                "{name} must be refused ({})",
                str_of(case, "why")
            );
        }
    }
}

#[test]
fn pay1_writers_refuse_what_their_readers_would() {
    use nfx_proto::pay::{Ack, MAX_INT, Message, ParseOptions, Quote, Rej, RejCode};
    let quote = |price, window, mints: Vec<&str>| {
        Message::Quote(Quote {
            price_per_chunk: price,
            mints: mints.into_iter().map(str::to_owned).collect(),
            window,
            served: 0,
            accepted_upto: 0,
            spent_total: 0,
        })
    };
    // A writer answers to the reader with the same options: loopback mints are written
    // only where they would be read.
    let loopback = quote(1, 8, vec!["http://127.0.0.1:3338"]);
    assert!(loopback.to_line().is_err());
    assert!(
        loopback
            .to_line_with(ParseOptions {
                allow_loopback_http: true
            })
            .is_ok()
    );
    assert!(quote(0, 8, vec!["https://m.example"]).to_line().is_err());
    assert!(quote(1, 0, vec!["https://m.example"]).to_line().is_err());
    assert!(quote(1, 1, vec!["https://m.example"]).to_line().is_err());
    assert!(quote(1, 65, vec!["https://m.example"]).to_line().is_err());
    assert!(quote(1, 64, vec!["https://m.example"]).to_line().is_ok());
    assert!(quote(1, 8, vec![]).to_line().is_err());
    assert!(quote(1, 8, vec!["https://m.example"]).to_line().is_ok());
    let ack = |n| {
        Message::Ack(Ack {
            accepted_upto: n,
            spent_total: n,
        })
    };
    assert!(ack(MAX_INT).to_line().is_ok());
    assert!(ack(MAX_INT + 1).to_line().is_err());
    // A known code built as `Other` does not survive its reader; `from_code` does.
    let rej = |code| Message::Rej(Rej { code, detail: None });
    assert!(rej(RejCode::Other("underpaid".into())).to_line().is_err());
    assert_eq!(RejCode::from_code("underpaid"), RejCode::Underpaid);
    assert_eq!(
        RejCode::from_code("mint-unavailable"),
        RejCode::MintUnavailable
    );
    assert!(rej(RejCode::MintUnavailable).to_line().is_ok());
    assert!(
        rej(RejCode::from_code("some-future-code"))
            .to_line()
            .is_ok()
    );
}
