//! Every NFX test vector (`spec/test-vectors/`, generated by `generate.py`), checked
//! natively and on `wasm32` (`wasm-pack test --node`). Signed artifacts are reproduced
//! byte for byte from the published throwaway keys, not merely verified.

#![allow(clippy::unwrap_used, clippy::expect_used)]

#[cfg(target_arch = "wasm32")]
use wasm_bindgen_test::wasm_bindgen_test as test;

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as B64;
use nfx_proto::beacon::{Beacon, BeaconContent, Chunks, Endpoint};
use nfx_proto::canon;
use nfx_proto::event::{Event, public_key_hex};
use nfx_proto::gossip::{Envelope, Op};
use nfx_proto::hashlist::{HashList, Role, verify_file};
use nfx_proto::manifest::{License, Manifest};
use nfx_proto::namespace::{Namespace, VideoAddr, validate_video_id};
use nfx_proto::voucher::Voucher;
use nfx_proto::{KIND_BEACON, KIND_MANIFEST, sha256};
use serde_json::Value;

macro_rules! vector {
    ($name:literal) => {
        serde_json::from_str::<Value>(include_str!(concat!("../../../spec/test-vectors/", $name)))
            .expect(concat!("vector ", $name, " is JSON"))
    };
}

fn event(v: &Value) -> Event {
    serde_json::from_value(v.clone()).unwrap()
}

fn secret(v: &Value, who: &str) -> [u8; 32] {
    let hex = v["secret_keys_DO_NOT_USE"][who].as_str().unwrap();
    let mut out = [0u8; 32];
    hex::decode_to_slice(hex, &mut out).unwrap();
    out
}

fn resign(original: &Event, secret: &[u8; 32]) -> Event {
    Event::sign(
        secret,
        original.created_at,
        original.kind,
        original.tags.clone(),
        original.content.clone(),
    )
    .unwrap()
}

fn str_of<'a>(v: &'a Value, key: &str) -> &'a str {
    v[key]
        .as_str()
        .unwrap_or_else(|| panic!("{key} is a string"))
}

#[test]
fn manifest_licensed_parses_and_is_reproduced() {
    let v = vector!("manifest.json");
    let ev = event(&v["event"]);
    let m = Manifest::from_event(&ev).unwrap();
    assert_eq!(ev.kind, KIND_MANIFEST);
    assert_eq!(m.addr.to_string(), "nfx:mainnet:1:salt-flats-dusk");
    assert_eq!(m.segs, 7);
    let License::Licensed(terms) = &m.license else {
        panic!("licensed")
    };
    assert_eq!((terms.key_price, terms.split_bps), (200, 5000));
    assert_eq!(terms.mint, "https://mint.example");
    assert_eq!(
        terms.free_seeders,
        vec![public_key_hex(&secret(&v, "seeder")).unwrap()]
    );

    let again = resign(&ev, &secret(&v, "creator"));
    assert_eq!(again, ev, "id and sig reproduced byte for byte");
    assert_eq!(serde_json::to_value(&again).unwrap(), v["event"]);

    // The publisher side: `tags()` is the vector's tag list, so re-signing reproduces it.
    assert_eq!(m.tags(), ev.tags);
    let built = Event::sign(
        &secret(&v, "creator"),
        ev.created_at,
        KIND_MANIFEST,
        m.tags(),
        m.description.clone(),
    )
    .unwrap();
    assert_eq!(built, ev);
}

#[test]
fn manifest_open_parses_ignores_unknown_tags_and_is_reproduced() {
    let v = vector!("manifest-open.json");
    let ev = event(&v["event"]);
    let m = Manifest::from_event(&ev).unwrap();
    assert_eq!(m.license, License::Open);
    assert_eq!(m.price_hint, Some(0));
    assert_eq!(resign(&ev, &secret(&v, "creator")), ev);

    // `tags()` emits every tag it understands, in order, and nothing else.
    let known: Vec<_> = ev
        .tags
        .iter()
        .filter(|t| t[0] != "x-future-tag")
        .cloned()
        .collect();
    assert_eq!(m.tags(), known);
    let rebuilt = Event::sign(
        &secret(&v, "creator"),
        ev.created_at,
        KIND_MANIFEST,
        m.tags(),
        m.description.clone(),
    )
    .unwrap();
    assert_eq!(Manifest::from_event(&rebuilt).unwrap(), m);
}

#[test]
fn every_invalid_manifest_is_rejected_for_a_semantic_reason() {
    let v = vector!("manifest-invalid.json");
    let cases = v["cases"].as_array().unwrap();
    assert!(cases.len() >= 30);
    for case in cases {
        let name = str_of(case, "name");
        let ev = event(&case["event"]);
        assert!(
            Manifest::from_event(&ev).is_err(),
            "{name} must be rejected"
        );
        if !matches!(name, "bad-signature" | "id-mismatch") {
            ev.verify()
                .unwrap_or_else(|e| panic!("{name}: signature should be valid, got {e}"));
            assert_eq!(resign(&ev, &secret(&v, "creator")), ev, "{name} reproduced");
        }
    }
}

#[test]
fn beacon_parses_all_endpoint_types_and_is_reproduced() {
    let v = vector!("beacon.json");
    let now = v["now"].as_u64().unwrap();
    let ev = event(&v["event"]);
    assert_eq!(ev.kind, KIND_BEACON);
    let b = Beacon::from_event(&ev, now).unwrap();
    let manifest = Manifest::from_event(&event(&vector!("manifest.json")["event"])).unwrap();
    assert!(b.serves(&manifest));
    let open = Manifest::from_event(&event(&vector!("manifest-open.json")["event"])).unwrap();
    assert!(b.serves(&open), "same author and address, newer revision");
    assert_eq!(b.content.chunks, Chunks::All);
    let kinds: Vec<_> = b
        .content
        .endpoints
        .iter()
        .map(|e| match e {
            Endpoint::Iroh { .. } => "iroh",
            Endpoint::Https { .. } => "https",
            Endpoint::Webrtc { .. } => "webrtc",
            Endpoint::Hyper { .. } => "hyper",
        })
        .collect();
    assert_eq!(kinds, ["iroh", "https", "webrtc", "hyper"]);
    let webrtc = b.content.endpoints.iter().find_map(|e| match e {
        Endpoint::Webrtc { renditions, .. } => Some(renditions.clone()),
        _ => None,
    });
    assert_eq!(webrtc, Some(vec!["720p".to_string()]));
    assert!(b.content.skipped.is_empty());

    // The publisher side renders the exact content string and tags, and the event re-signs
    // identically.
    assert_eq!(b.content.to_content(), ev.content);
    assert_eq!(
        nfx_proto::beacon::tags(&manifest.a_tag(), ev.created_at, 120).unwrap(),
        ev.tags
    );
    assert_eq!(resign(&ev, &secret(&v, "seeder")), ev);
    for bad_ttl in [59, 121] {
        assert!(nfx_proto::beacon::tags(&manifest.a_tag(), ev.created_at, bad_ttl).is_err());
    }
    assert!(nfx_proto::beacon::tags("30023:ab:nfx:mainnet:1:x", ev.created_at, 120).is_err());
}

#[test]
fn every_invalid_beacon_is_rejected_and_unknown_endpoints_are_skipped() {
    let v = vector!("beacon-invalid.json");
    let now = v["now"].as_u64().unwrap();
    for case in v["cases"].as_array().unwrap() {
        let name = str_of(case, "name");
        let ev = event(&case["event"]);
        ev.verify()
            .unwrap_or_else(|e| panic!("{name}: signature should be valid, got {e}"));
        assert!(
            Beacon::from_event(&ev, now).is_err(),
            "{name} must be rejected"
        );
    }
    let only_unknown = Beacon::from_event(&event(&v["unknown_endpoint_only"]), now).unwrap();
    assert!(only_unknown.content.endpoints.is_empty());
    assert_eq!(only_unknown.content.skipped, ["carrier-pigeon"]);

    // The valid beacon is rejected once it expires or when the clock is far off.
    let good = event(&vector!("beacon.json")["event"]);
    assert!(Beacon::from_event(&good, good.created_at + 120).is_err());
    assert!(Beacon::from_event(&good, good.created_at - 901).is_err());
}

#[test]
fn hashlist_bytes_root_files_and_playlists() {
    let v = vector!("hashlist.json");
    let manifest = Manifest::from_event(&event(&vector!("manifest.json")["event"])).unwrap();
    let list: HashList = serde_json::from_value(v["hashlist"].clone()).unwrap();

    // Rendering reproduces the exact bytes the root commits to.
    let bytes = list.render();
    assert_eq!(
        hex::encode(sha256(&bytes)),
        str_of(&v, "rendered_bytes_sha256")
    );
    assert_eq!(sha256(&bytes), manifest.root);
    let verified = HashList::verify_for(&bytes, &manifest).unwrap();
    assert_eq!(verified, list);

    // Every fabricated file satisfies the Blossom rule; a flipped byte does not.
    for (name, b64) in v["fabricated"].as_object().unwrap() {
        let data = B64.decode(b64.as_str().unwrap()).unwrap();
        let entry = list
            .files
            .iter()
            .find(|f| f.sha256 == hex::encode(sha256(&data)));
        let entry = entry.unwrap_or_else(|| panic!("{name} is listed"));
        verify_file(&entry.sha256, &data).unwrap();
        let mut tampered = data.clone();
        tampered[0] ^= 1;
        assert!(verify_file(&entry.sha256, &tampered).is_err());
    }

    // Playlists: their bytes are listed, and every URI in them is a listed content name.
    for (name, text) in v["playlists"].as_object().unwrap() {
        let bytes = text.as_str().unwrap().as_bytes();
        let entry = list.files.iter().find(|f| &f.name == name).unwrap();
        verify_file(&entry.sha256, bytes).unwrap();
        list.check_playlist(bytes).unwrap();
    }
    // A playlist's content name identifies its rendition (NFX-10 §2 stream mapping).
    for r in &list.renditions {
        let playlist = list.files.iter().find(|f| f.name == r.playlist).unwrap();
        assert_eq!(
            list.rendition_for_playlist(&format!("{}.m3u8", playlist.sha256)),
            Some(r)
        );
    }
    let master = list
        .files
        .iter()
        .find(|f| f.role == Role::PlaylistMaster)
        .unwrap();
    assert_eq!(
        list.rendition_for_playlist(&format!("{}.m3u8", master.sha256)),
        None
    );
    let init = list.files.iter().find(|f| f.role == Role::Init).unwrap();
    assert_eq!(list.resolve(&format!("{}.mp4", init.sha256)), Some(init));
    assert_eq!(list.resolve("seg/0001.m4s"), None);
}

#[test]
fn every_invalid_hashlist_and_playlist_is_rejected() {
    let v = vector!("hashlist-invalid.json");
    for case in v["hashlists"].as_array().unwrap() {
        let name = str_of(case, "name");
        let bytes = B64.decode(str_of(case, "bytes_b64")).unwrap();
        let mut root = [0u8; 32];
        hex::decode_to_slice(str_of(case, "root"), &mut root).unwrap();
        let video = VideoAddr::parse(str_of(case, "video")).unwrap();
        let segs = case["segs"].as_u64().unwrap();
        assert!(
            HashList::verify(&bytes, &root, &video, segs).is_err(),
            "{name} must be rejected"
        );
    }
    let list: HashList =
        serde_json::from_value(vector!("hashlist.json")["hashlist"].clone()).unwrap();
    for case in v["playlists"].as_array().unwrap() {
        let name = str_of(case, "name");
        assert!(
            list.check_playlist(str_of(case, "playlist").as_bytes())
                .is_err(),
            "{name}"
        );
    }
}

#[test]
fn canon_cases() {
    let v = vector!("canon.json");
    for case in v["cases"].as_array().unwrap() {
        let name = str_of(case, "name");
        let got = canon::canonicalize(str_of(case, "input"));
        match case["canon"].as_str() {
            Some(expected) => assert_eq!(got.as_deref().unwrap(), expected, "{name}"),
            None => assert!(got.is_err(), "{name} must be rejected, got {got:?}"),
        }
    }
}

#[test]
fn voucher_is_reproduced_verified_and_bound_to_the_manifest() {
    let v = vector!("voucher.json");
    let sig = str_of(&v, "sig");
    let now = 1_790_000_030;
    let manifest = Manifest::from_event(&event(&vector!("manifest.json")["event"])).unwrap();
    assert_eq!(manifest.author, str_of(&v, "creator_pubkey"));
    assert_eq!(manifest.a_tag(), str_of(&v, "manifest_a"));

    let presenter = manifest_seeder(&manifest);
    let voucher = Voucher::verify(str_of(&v, "wire"), sig, &manifest, &presenter, now).unwrap();
    assert_eq!(voucher.canon().unwrap(), str_of(&v, "canon"));
    assert_eq!(hex::encode(voucher.digest().unwrap()), str_of(&v, "digest"));
    assert_eq!(voucher.sign(&secret(&v, "creator")).unwrap(), sig);
    assert_eq!(
        canon::canonicalize(str_of(&v, "wire")).unwrap(),
        str_of(&v, "canon")
    );

    // Presented by anyone but its seeder (NIP-98 signer), it is worthless.
    assert!(
        Voucher::verify(str_of(&v, "wire"), sig, &manifest, &manifest.author, now).is_err(),
        "wrong presenter"
    );

    // Bound to a licensed manifest that lists the seeder, by that manifest's author.
    let open = Manifest::from_event(&event(&vector!("manifest-open.json")["event"])).unwrap();
    assert!(
        Voucher::verify(str_of(&v, "wire"), sig, &open, &presenter, now).is_err(),
        "open manifest"
    );
    let mut not_listed = manifest.clone();
    if let License::Licensed(terms) = &mut not_listed.license {
        terms.free_seeders.clear();
    }
    assert!(
        Voucher::verify(str_of(&v, "wire"), sig, &not_listed, &presenter, now).is_err(),
        "not a free_seeder"
    );
    let mut other_author = manifest.clone();
    other_author.author = public_key_hex(&[7u8; 32]).unwrap();
    assert!(
        Voucher::verify(str_of(&v, "wire"), sig, &other_author, &presenter, now).is_err(),
        "wrong signer"
    );

    let tampered = serde_json::to_string(&v["tampered"]).unwrap();
    assert!(Voucher::verify(&tampered, sig, &manifest, &presenter, now).is_err());
    assert!(
        Voucher::verify(
            str_of(&v, "wire"),
            sig,
            &manifest,
            &presenter,
            voucher.not_after
        )
        .is_err(),
        "expired"
    );
}

fn manifest_seeder(manifest: &Manifest) -> String {
    match &manifest.license {
        License::Licensed(terms) => terms.free_seeders[0].clone(),
        License::Open => panic!("licensed vector"),
    }
}

#[test]
fn gossip_envelope_is_reproduced_and_verified() {
    let v = vector!("gossip.json");
    let addr = VideoAddr::parse("nfx:mainnet:1:salt-flats-dusk").unwrap();
    assert_eq!(hex::encode(addr.swarm_topic()), str_of(&v, "topic"));
    let now = 1_790_000_030;

    let env = Envelope::verify(str_of(&v, "wire"), &addr, now).unwrap();
    assert_eq!(env.op, Op::Here);
    assert_eq!(env.canon_body().unwrap(), str_of(&v, "canon"));
    assert_eq!(
        hex::encode(sha256(env.canon_body().unwrap().as_bytes())),
        str_of(&v, "digest")
    );
    assert_eq!(env.sign(&secret(&v, "seeder")).unwrap(), str_of(&v, "sig"));
    assert!(!env.is_stale(now));
    assert!(env.is_stale(env.created_at + 241));

    let other = VideoAddr::parse("nfx:testnet:1:salt-flats-dusk").unwrap();
    assert!(
        Envelope::verify(str_of(&v, "wire"), &other, now).is_err(),
        "foreign swarm"
    );
    let forged = str_of(&v, "wire").replace("\"here\"", "\"bye\"");
    assert!(
        Envelope::verify(&forged, &addr, now).is_err(),
        "op is signed"
    );
    // NFX-06 §4: envelopes are at most 4 KiB; padding a valid one past that is refused
    // before parsing (whitespace is layout, so the signature alone would still verify).
    let wire = str_of(&v, "wire");
    let padded = format!("{wire}{}", " ".repeat(4097 - wire.len()));
    assert!(Envelope::verify(&padded, &addr, now).is_err(), "over 4 KiB");
    let fits = format!("{wire}{}", " ".repeat(4096 - wire.len()));
    assert!(
        Envelope::verify(&fits, &addr, now).is_ok(),
        "exactly 4 KiB is fine"
    );
}

#[test]
fn derived_identifiers_and_grammar() {
    let v = vector!("derived.json");
    for d in v["videos"].as_array().unwrap() {
        let addr = VideoAddr::parse(str_of(d, "d")).unwrap();
        assert_eq!(addr.namespace().to_string(), str_of(d, "namespace"));
        assert_eq!(addr.video_id(), str_of(d, "video_id"));
        assert_eq!(hex::encode(addr.swarm_topic()), str_of(d, "swarm_topic"));
        for w in d["web_swarms"].as_array().unwrap() {
            let rendition = str_of(w, "rendition");
            assert_eq!(
                addr.web_stream_swarm_id(rendition),
                str_of(w, "stream_swarm_id")
            );
            assert_eq!(
                addr.web_tracker_infohash(rendition),
                str_of(w, "tracker_infohash")
            );
        }
        assert_eq!(hex::encode(addr.hyper_topic()), str_of(d, "hyper_topic"));
    }
    let a = &v["a_tag"];
    let manifest = Manifest::from_event(&event(&vector!("manifest.json")["event"])).unwrap();
    assert_eq!(manifest.a_tag(), str_of(a, "a"));
    assert_eq!(manifest.author, str_of(a, "creator"));

    for ns in v["namespaces_valid"].as_array().unwrap() {
        let ns = ns.as_str().unwrap();
        assert_eq!(Namespace::parse(ns).unwrap().to_string(), ns);
    }
    for ns in v["namespaces_invalid"].as_array().unwrap() {
        assert!(
            Namespace::parse(ns.as_str().unwrap()).is_err(),
            "{ns} must be rejected"
        );
    }
    for id in v["video_ids_valid"].as_array().unwrap() {
        validate_video_id(id.as_str().unwrap()).unwrap();
    }
    for id in v["video_ids_invalid"].as_array().unwrap() {
        assert!(
            validate_video_id(id.as_str().unwrap()).is_err(),
            "{id} must be rejected"
        );
    }
}

#[test]
fn beacon_content_round_trips_through_its_own_parser() {
    let ev = event(&vector!("beacon.json")["event"]);
    let content: Value = serde_json::from_str(&ev.content).unwrap();
    let parsed = BeaconContent::from_json(&content).unwrap();
    assert_eq!(
        BeaconContent::from_json(&serde_json::from_str(&parsed.to_content()).unwrap()).unwrap(),
        parsed
    );
}

#[test]
fn licensed_encryption_is_reproduced_by_rustcrypto() {
    use chacha20poly1305::XChaCha20Poly1305;
    use chacha20poly1305::aead::{Aead, KeyInit, Payload};

    // libsodium generated this vector; RustCrypto must produce the same bytes (NFX-08 §2).
    let v = vector!("licensed.json");
    let key = secret(&v, "video_key");
    let mut nonce = [0u8; 24];
    hex::decode_to_slice(str_of(&v, "nonce"), &mut nonce).unwrap();
    let plaintext = B64.decode(str_of(&v, "plaintext_b64")).unwrap();
    let stored = B64.decode(str_of(&v, "stored_b64")).unwrap();
    let aad = str_of(&v, "aad");
    assert_eq!(
        aad,
        format!("{}/{}", str_of(&v, "video"), str_of(&v, "name"))
    );

    let cipher = XChaCha20Poly1305::new(&key.into());
    let ciphertext = cipher
        .encrypt(
            &nonce.into(),
            Payload {
                msg: &plaintext,
                aad: aad.as_bytes(),
            },
        )
        .unwrap();
    assert_eq!(
        [nonce.as_slice(), &ciphertext].concat(),
        stored,
        "byte for byte"
    );
    assert_eq!(hex::encode(sha256(&stored)), str_of(&v, "stored_sha256"));

    let (n, ct) = stored.split_at(24);
    let nonce_in: [u8; 24] = n.try_into().unwrap();
    let opened = cipher
        .decrypt(
            &nonce_in.into(),
            Payload {
                msg: ct,
                aad: aad.as_bytes(),
            },
        )
        .unwrap();
    assert_eq!(opened, plaintext);
    let moved = cipher.decrypt(
        &nonce_in.into(),
        Payload {
            msg: ct,
            aad: str_of(&v, "wrong_aad").as_bytes(),
        },
    );
    assert!(moved.is_err(), "a file in the wrong place must not decrypt");
}
